# Generated by Django 3.0 on 2024-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulations',
            fields=[
                ('formulation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('formulation_name', models.CharField(max_length=10)),
                ('pbt', models.FloatField(default=0)),
                ('tdi', models.FloatField(default=0)),
                ('tri_bis', models.FloatField(default=0)),
                ('athree', models.FloatField(default=0)),
                ('bonding_agent', models.FloatField(default=0)),
                ('ap_small', models.FloatField(default=0)),
                ('ap_large', models.FloatField(default=0)),
                ('ai_powder', models.FloatField(default=0)),
                ('tmp', models.FloatField(default=0)),
                ('die_gly', models.FloatField(default=0)),
                ('tri_glycol', models.FloatField(default=0)),
                ('add_tdi', models.FloatField(default=0)),
            ],
        ),
    ]
