# Generated by Django 3.0 on 2024-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('temp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('temp_value', models.IntegerField(default=0)),
            ],
        ),
    ]
