# Generated by Django 3.0 on 2024-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rheological_data',
            name='state_mark',
            field=models.CharField(max_length=50),
        ),
    ]
