# Generated by Django 3.0 on 2024-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhdata', '0002_auto_20240122_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rheological_data',
            name='rh_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
